name: deploy to staging lambda

on:
  pull_request:
  push:
    branches: [main]

jobs:
  deploy:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run a multi-line script
        run: |
          python -m pip install --upgrade pip
          #install all dependencies as defined by requirements.txt in the current directory
          pip3 install -r requirements.txt -t .
          #zip files into current directory
          zip -r bundle.zip .

      - name: AWS Lambda deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          function_name: otpService-staging
          zip_file: bundle.zip
